# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.boot_timeout = 1000
  config.vm.network "forwarded_port", guest: 80, host: 8080 # 포트포워딩 설정 . 
  config.vm.define "master" do |master| # | | 내부는 alias, 첫글자는 대문자가 올 수 없다.
    master.vm.box = "ubuntu/focal64"
    master.vm.host_name = "master"
    master.vm.network "public_network", ip: "192.168.50.10"
    master.vm.synced_folder "./join", "/home/vagrant/join"
    master.vm.provider :virtualbox do |masterSpec|
      masterSpec.memory = 4096
      masterSpec.cpus = 4
    end
    master.vm.provision "shell", path: "./script/common_config.sh"
    master.vm.provision "shell", path: "./script/master.sh"
  end

  (1..2).each do |n|
    config.vm.define "worker-#{n}" do |worker|
      worker.vm.box = "ubuntu/focal64"
      worker.vm.host_name = "worker-#{n}"
      worker.vm.network "public_network", ip: "192.168.50.1#{n}"
      worker.vm.synced_folder "./join", "/home/vagrant/join"
      worker.vm.provider :virtualbox do |workerSpec|
        workerSpec.memory = 4096
        workerSpec.cpus = 4
      end
      worker.vm.provision "shell", path: "./script/common_config.sh"
      worker.vm.provision "shell", path: "./script/worker.sh"
    end


  end
end